stages:
  - test

# Definição dos jobs do pipeline
test:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - python -m pytest
  artifacts:
    paths:
      - test_results/
  tags:
    - hardware-testing

# Definição da notificação em caso de falha
notify_failure:
  stage: test
  script:
    - echo "Pipeline falhou!"  # Mensagem de alerta
    # Comando para enviar notificação para o Slack
    - 'curl -X POST -H "Content-type: application/json" --data "{\"text\":\"Pipeline falhou!\"}" https://hooks.slack.com/services/XXXXXXXXX/YYYYYYYYY/ZZZZZZZZZZZZZZZZZZZZZZZZ'
  when: on_failure  # Executa apenas em caso de falha
